Cli gas estimate
PolymathNetwork/polymath-core pull request #160
Opened 2018-06-29 13:25 UTC by VictorVicente

2018-07-01 04:08 UTC, satyamakgec requested changes
Getting a revert error! when muliMint script run at the time of creation of ST20Generator
`Press "Y" if you have a list of affiliates addresses with you otherwise hit Enter and get the minted tokens to a particular address: Y`.

2018-07-02 12:23 UTC, pabloruiz55 commented
This is partly my fault since I changed one address in the whitelist csv and not the mint, so it's basically trying to mint tokens to a non-whitelisted address, reverting and making the whole script exit.

As Victor indicated, this happens on master too. He's going to fix it by catching the transfer error before attempting to blindly transfer.

2018-07-02 15:21 UTC, pabloruiz55 approved these changes

2018-07-02 15:32 UTC, satyamakgec approved these changes

2018-07-02 15:33 UTC, merged