Check pause flow
PolymathNetwork/polymath-core pull request #285
Opened 2018-09-27 14:56 UTC by satyamakgec

### Please check if the PR fulfills these requirements
- [ ] The commit message follows our Submission guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? 
(Bug fix, feature, docs update, ...)

### What is the current behavior? 
(You can also link to an open issue here)
Merge only when the `upgrade-mr` PR get merge as I take that upgrade-mr as a base branch

### What is the new behavior?
(Define and describe any new functionality. Clarify if this is a feature change)

### Does this PR introduce a breaking change?
(What changes might users need to make in their application due to this PR?)

### Any Other information:

2018-09-27 20:11 UTC, pabloruiz55 commented
PR looks good. Only wondering why all those commits are showing up in the PR. @satyamakgec

2018-09-27 20:49 UTC, adamdossa requested changes

2018-09-27 20:49 UTC, adamdossa commented on contracts/SecurityTokenRegistry.sol
>      modifier whenNotPaused() {
Can you rename to something like whenNotPausedOrOwner - `whenNotPaused` might be a bit confusing as it's a standard function with a different normal implementation.

2018-09-27 20:49 UTC, adamdossa commented on contracts/ModuleRegistry.sol
> +    function pause() external onlyOwner {
I think `pause` should revert if the contract is already paused. It makes the logs easier to interpret. Can we have `whenNotPaused` and `whenNotPausedOrOwner` and use `whenNotPaused` here maybe?

2018-09-28 07:57 UTC, satyamakgec commented
@pabloruiz55 the cause of showing all other commits was `upgrade-mr` branch as I create this branch from the upgrade-mr branch. not it doesn't show those commits as we merge the upgrade-mr branch.

2018-09-28 10:46 UTC, adamdossa approved these changes

2018-09-28 10:47 UTC, merged