[Feature] Create checkpoint function in checkpoint modules
PolymathNetwork/polymath-core pull request #353
Opened 2018-10-19 06:39 UTC by maxsam4

### Please check if the PR fulfills these requirements
- [X] The commit message follows our Submission guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? 
Added createCheckpoint function to dividend checkpoint modules

### Does this PR introduce a breaking change?
No

2018-10-19 15:04 UTC, pabloruiz55 approved these changes

2018-10-19 15:05 UTC, pabloruiz55 requested changes
We should add the same test case to f_ether_dividends.js as well.

2018-10-19 16:20 UTC, VictorVicente commented
You should also add this to docs/permissions_list.md before merge

2018-10-19 17:45 UTC, maxsam4 commented
We'll do it in https://github.com/PolymathNetwork/polymath-core/pull/347 to avoid merge conflicts.

2018-10-22 12:58 UTC, satyamakgec approved these changes

2018-10-22 12:59 UTC, pabloruiz55 approved these changes

2018-10-22 12:59 UTC, merged