[WIP] USD Tiered STO changes
PolymathNetwork/polymath-core pull request #397
Opened 2018-11-08 11:43 UTC by maxsam4

TODO: Add test cases, update changelog, cleanup comments, look into getSTODetails.

Maybe do: Revert back to regular deployment rather than proxy as contract size has reduced.

2018-11-08 14:44 UTC, maxsam4 commented
Test cases added, comments cleaned up
TODO: update changelog, look into getSTODetails, revert to classic factory.

2018-11-09 09:21 UTC, maxsam4 commented
It still did not fit in the factory so we are gonna stick with proxy deployer for now.
Added getSTODetails to it and updated changelog.

2018-11-12 08:35 UTC, satyamakgec requested changes
not fully reviewed yet (WIP) but you can correct those if you want @maxsam4

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    function modifyFunding(FundRaiseType[] _fundRaiseTypes) external {
Why its permission gets removed? Now anybody can change the fundRaiseType

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    ) external onlyFactoryOrOwner {
use the internal version of modifyLimits() ~ _modifyLimits(). and use the OnlyOwner permission

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    ) external onlyFactoryOrOwner {
use onlyOwner modifier here

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    ) external onlyFactoryOrOwner {
use onlyOwner() modifier

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    ) external onlyFactoryOrOwner {
use onlyOwner() modifer

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
This function is allowing to change the no. of tiers. If STO has 5 tiers and If Issuer wants only to change the 3 tiers data (Allowed by the function no restriction that checked the length of arrays should be equal to no. of tiers) then this function will first delete all the 5 tiers data and then push the 3 new tiers data.
Possible simple solution:
add this `require(_ratePerTier.length == tiers.length);`  in modifyTiers() function.

So using the above require statement issuer always get restricted to change the all tiers data at once. AFAICT this was not a problem in the previous implementation.

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    function buyWithPOLY(address _beneficiary, uint256 _investedPOLY) public {
add validPOLY() modifier

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +    function buyWithPOLY(address _beneficiary, uint256 _investedPOLY) public {
prefer to call buyWithPOLYRateLimited() instead of _buyWithTokens()

2018-11-12 08:35 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +        _buyWithTokens(_beneficiary, _investedDAI, FundRaiseType.DAI, 0);
prefer to call buyWithPOLYRateLimited() instead of _buyWithTokens() for consistency in all functions

2018-11-12 08:41 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +    function modifyFunding(FundRaiseType[] _fundRaiseTypes) external {
Must have done by mistake. Will add onlyOwner.

2018-11-12 08:42 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +    ) external onlyFactoryOrOwner {
I kept the permission same as earlier but you're right, we don't need factory permission. Will change in all.

2018-11-12 08:44 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
This is not a problem IMO, this is as I intended it to be. I wanted issuer to be able to change the number of tiers. The dApp can be programmed to send existing data to the function along with changed data.

2018-11-12 08:59 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
Also, the same thing was happening in the last implementation as well. You were not allowed to edit specific tiers. You needed to feed all tiers to the function even if you want to edit only one. The only difference is that I have explicitly added `delete` while the last implementation just overwrites on storage. 

If needed, I can add a separate function that will edit one tier at a time. Although I believe that dApp should be able to handle that.

2018-11-12 09:30 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
Yes, In last implementation you can't change the specific tier data but if I want to change the data of the first three tiers then you can change also that will also not effect on the current no. of tiers.

Yes dApp can be programmed but we also need to take care when someone uses our smart contract directly (without any dApp).

2018-11-12 09:35 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
No, you can't change data of only first 3 tiers in the last implementation. The code replaces the storage array with one passed in the function. If the input had only 3 tiers data, Storage will now have only 3 tiers data.

I'll add the function to edit a single tier. Although I highly doubt that anyone will use smart contracts directly for a function available in the dApp.

2018-11-12 09:45 UTC, maxsam4 commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
There isn't even an event to show single tier change. I can populate the list in a memory array for the event but I just can't justify it. We can't even edit other parameters like startTime / endTime separately with current code. The file size is already so big that we are forced to use proxy deployment. I don't think we should be adding this feature.

2018-11-12 12:39 UTC, satyamakgec requested changes

2018-11-12 12:39 UTC, satyamakgec commented on CHANGELOG.md
> +* Added `buyWithETHRateLimited`, `buyWithPOLYRateLimited` and `buyWithUSDRateLimited` to USDTSTO.
create the 2.x.x release and add these changes into that.

2018-11-12 12:39 UTC, satyamakgec commented on CHANGELOG.md
> +* Individual mappings for tier data removed in UDSTSTO.
create the 2.x.x release and add these changes into that.

2018-11-12 12:39 UTC, satyamakgec commented on contracts/modules/STO/USDTieredSTO.sol
> +        delete tiers;
okay cool, could you please add the developer comment about the behavior of the function.

2018-11-12 12:55 UTC, satyamakgec commented
@maxsam4 could you please elaborate why you are using the `_minTokens` check in the contract. as far I understand it is only used to check the minimum demand of tokens for a buy call.

2018-11-12 14:25 UTC, maxsam4 commented
@satyamakgec Yes, you are right. It is one of the Audit suggestions that a user must be able to set the minimum amount of tokens bought in the STO or the min conversion rate and max token rate. This is because the rate can be different at the time transaction is created and mined. I have kept the old functions intact so if a user does not want to limit the rate, they can choose to do so. As an investor, I don't want to buy tokens at a price much higher than what I signed up for. This can happen in case where POLY discount token limit is reached by some other tx before our tx is mined, tier changes before our tx is mined, eth suddenly crashes etc.

2018-11-12 14:36 UTC, maxsam4 commented on CHANGELOG.md
> +* Added `buyWithETHRateLimited`, `buyWithPOLYRateLimited` and `buyWithUSDRateLimited` to USDTSTO.
Will do it along with missing code documentation tomorrow.

2018-11-13 12:06 UTC, satyamakgec commented
I am done with the reviewing part @adamdossa please take a final look.

2018-11-13 12:50 UTC, adamdossa approved these changes

2018-11-13 12:50 UTC, adamdossa commented
I reviewed and approved. Just one question - what was the reason to push the `gotoNextTier` logic down into the function rather than the previous logic?

2018-11-13 12:57 UTC, maxsam4 commented
> @maxsam4 I reviewed and approved. Just one question - what was the reason to push the `gotoNextTier` logic down into the function rather than the previous logic?

With the new logic, only granular units of tokens are purchased which means not all the InvestedUSD may be consumed. We don't need to go to the next tier in this scenario.

For example, If I have an invisible token which costs 10 a pop and an Investor invests 15 USD then the first tier will buy him 1 token and return from the function. Earlier logic would have seen pending 5 USD and called the next tier. In this case, we don't need to call the next tier. We just need to refund the 5USD back to the investor.

2018-11-13 13:09 UTC, adamdossa commented
Got it thanks - that makes sense.

2018-11-13 13:20 UTC, satyamakgec approved these changes

2018-11-21 05:26 UTC, maxsam4 commented
@VictorVicente I've added view functions that were required for CLI and dApp.

@satyamakgec @adamdossa I've made some structural changes in `_buyTokens` and its internal functions to reduce code redundancy. Please review again.

I'll add test cases for the new `view` functions in a bit.

2018-11-21 15:44 UTC, FOBCrypto commented
typo at line 487 of investor_portal.js "You are going to spen**t**" should be "you are going to spen**d**"

2018-11-22 10:16 UTC, maxsam4 commented
> typo at line 487 of investor_portal.js "You are going to spen**t**" should be "you are going to spen**d**"

Thanks for pointing that out @FOBCrypto .
Would you like to use the new GitHub beta suggestion feature to suggest that change? That way the commit will be linked to your GitHub profile and you'll officially become a contributor :).

2018-11-22 11:02 UTC, FOBCrypto commented on CLI/commands/investor_portal.js
> +    console.log(chalk.yellow(`You are going to spent ${web3.utils.fromWei(tokensToBuy.spentValue)} ${raiseType} (${web3.utils.fromWei(tokensToBuy.spentUSD)} USD) to buy ${web3.utils.fromWei(minTokenT
```suggestion
    console.log(chalk.yellow(`You are going to spend ${web3.utils.fromWei(tokensToBuy.spentValue)} ${raiseType} (${web3.utils.fromWei(tokensToBuy.spentUSD)} USD) to buy ${web3.utils.fromWei(minTokenToBuy)} ${STSymbol} approx.`));
```

2018-11-25 17:34 UTC, merged