WIP - Module labeling
PolymathNetwork/polymath-core pull request #428
Opened 2018-11-22 10:30 UTC by comeonbuddy

### Please check if the PR fulfills these requirements
- [ ] The commit message follows our Submission guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? 
(Bug fix, feature, docs update, ...)

### What is the current behavior? 
(You can also link to an open issue here)

### What is the new behavior?
(Define and describe any new functionality. Clarify if this is a feature change)

### Does this PR introduce a breaking change?
(What changes might users need to make in their application due to this PR?)

### Any Other information:

2018-11-23 21:54 UTC, satyamakgec requested changes

2018-11-23 21:54 UTC, satyamakgec commented on contracts/tokens/SecurityToken.sol
> +    ) onlyOwner nonReentrant {
add `public` explicitly

2018-11-23 21:54 UTC, satyamakgec commented on contracts/tokens/SecurityToken.sol
> +        return addModuleWithLabel(_moduleFactory, _data, _maxCost, _budget, "");
no need of `return`

2018-11-27 10:54 UTC, comeonbuddy commented on contracts/tokens/SecurityToken.sol
> +    ) onlyOwner nonReentrant {
done

2018-11-27 10:54 UTC, comeonbuddy commented on contracts/tokens/SecurityToken.sol
> +        return addModuleWithLabel(_moduleFactory, _data, _maxCost, _budget, "");
done

2018-11-27 16:49 UTC, satyamakgec approved these changes

2018-11-27 16:50 UTC, merged