[WIP] [CLI] Move mint, accredit and nonAccreditLimit code to its corresponding module script
PolymathNetwork/polymath-core pull request #446
Opened 2018-11-29 18:40 UTC by shuffledex

2018-11-29 19:11 UTC, VictorVicente requested changes

2018-11-29 19:11 UTC, VictorVicente commented on CLI/commands/sto_manager.js
> +        await startCSV(tokenSymbol, 75, 'nonAccredited');
Change 'nonAccredited` to `nonAccreditedLimit`

2018-11-29 19:11 UTC, VictorVicente commented on CLI/commands/sto_manager.js
> +  for (let i = 0; i < distribData.length; i++) {
Why are there two `for` blocks?

2018-11-30 12:03 UTC, shuffledex commented on CLI/commands/sto_manager.js
> +  for (let i = 0; i < distribData.length; i++) {
Interesting... I never touched this part of the code. Maybe a type error? or something intentional?

2018-11-30 12:03 UTC, shuffledex commented on CLI/commands/sto_manager.js
> +        await startCSV(tokenSymbol, 75, 'nonAccredited');
ok

2018-12-03 22:21 UTC, VictorVicente approved these changes

2018-12-03 22:23 UTC, merged